### ISSUE TITLE
reverse-context.js added twice due to failing filter guard on Windows

### ISSUE THREAD

**Issue by knyy** [sabberworm/karma-iframes#6]
**Issue:**
On Windows only, the reverse-context script is added twice, this causes the context to not be setup properly.

**Cause:**
In rewrite-middleware.js
```javascript
.filter(file => file.originalPath !== REVERSE_CONTEXT);
```
Does not evaluate to through for reverse-context filepath on windows as require-resolve does not normalize path separators.

REVERSE_CONTEXT 

**Resolution:**
In frameworks.js when require resolving REVERSE_CONTEXT
```
let REVERSE_CONTEXT = require.resolve('../static/reverse-context.js').split(path.sep).join('/');
```
And change rewrite-middleware.js Line 74
```
return (file.originalPath === REVERSE_CONTEXT) || (file.originalPath === REVERSE_CONTEXT.split(path.sep).join('/')));
```
to 
```
  return file.originalPath === REVERSE_CONTEXT;
```

**Comment by sabberworm** [comment]
Thanks for the bug report and investigation. If you could open a PR, I’ll gladly merge it…
